name: Generate ASCII Art

on: push

jobs:
 build_job_1:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repos
          uses: actions/checkout@v7

        - name: List files
          run: ls -ltra

        - name: Install cowsay Program
          run: sudo apt-get install cowsay -y
        
        - name: Execute cmd cowsay
          run: cowsay -f dragon "Run for cover, I'm a dragon!" >> dragon.txt

        - name: Upload dragon.txt as artifact
          uses: actions/upload-artifact@v7
          with:
            name: dragon-artifact
            path: dragon.txt
 test_job_1:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
        - name: Download dragon.txt as artifact
          uses: actions/download-artifact@v8
          with:
            name: dragon-artifact
            path: dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: test file exist
          run: grep -i "dragon" dragon.txt
 deploy_job_1:
    needs: test_job_1
    runs-on: ubuntu-latest
    steps:
        - name: Sleep for 30 seconds
          run: sleep 30

        - name: Read file
          run: cat dragon.txt

        - name: test file exist
          run: grep -i "dragon" dragon.txt